<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-31T08:08:15 IST" name="Suite" finished-at="2025-01-31T08:08:33 IST" duration-ms="17577">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginwithInvalidCredentials()[pri:0, instance:muthusundar.ErrorValidationTest@5db6b9cd]" name="loginwithInvalidCredentials" class="muthusundar.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" name="submitOrder" class="muthusundar.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-01-31T08:08:15 IST" name="Error Validation Test" finished-at="2025-01-31T08:08:27 IST" duration-ms="11623">
      <class name="muthusundar.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:muthusundar.ErrorValidationTest@5db6b9cd]" started-at="2025-01-31T08:08:16 IST" name="launchApplication" finished-at="2025-01-31T08:08:24 IST" duration-ms="8517" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginwithInvalidCredentials()[pri:0, instance:muthusundar.ErrorValidationTest@5db6b9cd]" started-at="2025-01-31T08:08:24 IST" name="loginwithInvalidCredentials" finished-at="2025-01-31T08:08:27 IST" duration-ms="2600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:muthusundar.ErrorValidationTest@5db6b9cd]" started-at="2025-01-31T08:08:27 IST" name="tearDown" finished-at="2025-01-31T08:08:27 IST" duration-ms="444" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- muthusundar.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2025-01-31T08:08:15 IST" name="Submit Order Test" finished-at="2025-01-31T08:08:33 IST" duration-ms="17577">
      <class name="muthusundar.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:16 IST" name="launchApplication" finished-at="2025-01-31T08:08:24 IST" duration-ms="8163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:24 IST" name="submitOrder" data-provider="getData" finished-at="2025-01-31T08:08:27 IST" duration-ms="2991" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sundar@04, email=muthusundar044@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at muthusundar.pageobjects.ProductCatalogue.addProductToCart(ProductCatalogue.java:48)
at muthusundar.SubmitOrderTest.submitOrder(SubmitOrderTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:27 IST" name="tearDown" finished-at="2025-01-31T08:08:28 IST" duration-ms="308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:28 IST" name="launchApplication" finished-at="2025-01-31T08:08:32 IST" duration-ms="3860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:32 IST" name="submitOrder" data-provider="getData" finished-at="2025-01-31T08:08:33 IST" duration-ms="1068" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sundar@04, email=muthusundar044@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at muthusundar.pageobjects.ProductCatalogue.addProductToCart(ProductCatalogue.java:48)
at muthusundar.SubmitOrderTest.submitOrder(SubmitOrderTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:33 IST" name="tearDown" finished-at="2025-01-31T08:08:33 IST" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:muthusundar.SubmitOrderTest@17fc391b]" started-at="2025-01-31T08:08:33 IST" name="OrderHistoryTest" finished-at="2025-01-31T08:08:33 IST" depends-on-methods="muthusundar.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method muthusundar.SubmitOrderTest.OrderHistoryTest() on instance muthusundar.SubmitOrderTest@17fc391b depends on not successfully finished methods 
[muthusundar.SubmitOrderTest.submitOrder() on instance muthusundar.SubmitOrderTest@17fc391b]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method muthusundar.SubmitOrderTest.OrderHistoryTest() on instance muthusundar.SubmitOrderTest@17fc391b depends on not successfully finished methods 
[muthusundar.SubmitOrderTest.submitOrder() on instance muthusundar.SubmitOrderTest@17fc391b]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- muthusundar.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
